[package]
name = "bootleg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.3.2"
clap = { version = "4.5.4", features = ["derive"] }
clap-help = "1.2.0"
crossterm = "0.27.0"
miette = { version = "7.2.0", features = ["fancy"] }
termimad = "0.29.1"
thiserror = "1.0.59"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"

